<!--
/**
 * KtogiasZendLib (https://github.com/ktogias/KtogiasZendLib)
 *
 * @link      https://github.com/ktogias/KtogiasZendLib for the canonical source repository
 * @copyright Copyright (c) Konstantinos Togias (https://ktogias.gr)
 * @license   https://raw.githubusercontent.com/ktogias/KtogiasZendLib/master/LICENSE New BSD License
 */
-->
<div class="row">
    
    <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3" id="main-main-area" ng-view></div>
</div>