<!--
/**
 * KtogiasZendLib (https://github.com/ktogias/KtogiasZendLib)
 *
 * @link      https://github.com/ktogias/KtogiasZendLib for the canonical source repository
 * @copyright Copyright (c) Konstantinos Togias (https://ktogias.gr)
 * @license   https://raw.githubusercontent.com/ktogias/KtogiasZendLib/master/LICENSE New BSD License
 */
-->
<div>
   
    <p>
        {{'Εισάγετε' | translate}}:
    </p>
    <ul>
        <li>{{'Στο πεδίο "Όνομα χρήστη"' | translate}}: <br/>{{'Το όνομα χρήστη που σας έχει δοθεί για την πρόσβαση στην εφαρμογή.' | translate}}</li>
        <li>{{'Στο πεδίο "Κωδικός πρόσβασης"'| translate}}: <br/>{{'Τον κωδικό που σας έχει δοθεί για την πρόσβαση στην εφαρμογή.' | translate}}</li>
    </ul>
</div>