<!--
/**
 * KtogiasZendLib (https://github.com/ktogias/KtogiasZendLib)
 *
 * @link      https://github.com/ktogias/KtogiasZendLib for the canonical source repository
 * @copyright Copyright (c) Konstantinos Togias (https://ktogias.gr)
 * @license   https://raw.githubusercontent.com/ktogias/KtogiasZendLib/master/LICENSE New BSD License
 */
-->
<div id="login-panel" class="panel panel-default" ng-controller="ktogiasretrievepasswordController as controller">
    <div class="panel-heading">
        {{'Ανάκτηση κωδικού χρήστη' | translate}}
        <a role="button" title="{{'Βοήθεια' | translate}}"
            uib-popover-template="'ktogias-login/retrieve-password-help.phtml'"
            popover-title="{{'Ανάκτηση κωδικού χρήστη'|translate}} - {{'Βοήθεια'|translate}}"
            popover-placement="bottom-left"
            popover-trigger="outsideClick"
            popover-append-to-body="true"
            >
            <span
                class="glyphicon glyphicon-question-sign" 
             ></span>
        </a>
    </div>
    <div class="panel-body">
        <div ng-show="!controller.successMessages">
            <p>
                {{'Συμπληρώστε το email σας ή το όνομα χρήστη και πατήστε "Ανάκτηση κωδικού".' | translate}}
                {{'Ένα email με οδηγίες για την ανάκτηση του κωδικού σας θα αποσταλεί στο email σας.' | translate}}
            </p>
             <form name="retrieveForm" role="form">
                <div class="control-group form-group" ng-class="{error: retrieveForm.usernameOrEmail.$invalid && !retrieveForm.usernameOrEmail.$pristine}">
                    <label for="retrieveForm-usernameOrEmail">{{'Email ή όνομα χρήστη' | translate}}</label>
                    <input class="form-control" id="retrieveForm-username" type="text" name="usernameOrEmail" 
                           placeholder="{{'Εισάγετε το email σας ή το όνομα χρήστη (έως 100 χαρακτήρες)' | translate}}" 
                           ng-model="controller.usernameOrEmail"  
                           required minlength="1" maxlength="100"/>
                    <span ng-show="retrieveForm.usernameOrEmail.$error.required && !retrieveForm.usernameOrEmail.$pristine" class="help-block">
                        {{'Το πεδίο δεν πρέπει να είναι κενό.' | translate}}
                    </span>
                    <span ng-show="retrieveForm.usernameOrEmail.$error.maxlength && !retrieveForm.usernameOrEmail.$pristine" class="help-block">
                        {{'Το μήκος δεν πρέπει να ξεπερνά τους 100 χαρακτήρες.' | translate}}
                    </span>
                </div>
                <div class="control-group form-group">
                    <button ng-click="controller.retrieve()" 
                            ng-disabled="retrieveForm.$pristine || retrieveForm.$invalid"
                            class="btn btn-primary">{{'Ανάκτηση κωδικού' | translate}}</button>    
                    <button type='button' ng-click="controller.clear();" ng-disabled="retrieveForm.$pristine"
                            class="btn btn-primary">{{'Καθαρισμός' | translate}}</button>
                </div>
             </form>
        </div>
        <div ng-show="controller.successMessages" style=" color: darkgreen">
            <p ng-repeat="message in controller.successMessages">
                {{message | translate}}
            </p>
        </div>
    </div>
    <div class="panel-footer">
        <button ng-click="controller.goToLoginForm()" 
                class="btn btn-default">{{'Επιστροφή στην οθόνη εισόδου' | translate}}</button>
    </div>
</div>