<!--
/**
 * KtogiasZendLib (https://github.com/ktogias/KtogiasZendLib)
 *
 * @link      https://github.com/ktogias/KtogiasZendLib for the canonical source repository
 * @copyright Copyright (c) Konstantinos Togias (https://ktogias.gr)
 * @license   https://raw.githubusercontent.com/ktogias/KtogiasZendLib/master/LICENSE New BSD License
 */
-->
<span ng-if="!clickable" ng-bind-html="valueCtrl.val.value | translate"></span>
<a ng-if="clickable" class="clickable" ng-click="valueCtrl.callAction(clickAction,clickArg)">
    <span ng-bind-html="valueCtrl.val.value | translate"></span>
</a>
