<!--
/**
 * KtogiasZendLib (https://github.com/ktogias/KtogiasZendLib)
 *
 * @link      https://github.com/ktogias/KtogiasZendLib for the canonical source repository
 * @copyright Copyright (c) Konstantinos Togias (https://ktogias.gr)
 * @license   https://raw.githubusercontent.com/ktogias/KtogiasZendLib/master/LICENSE New BSD License
 */
-->
<span ng-bind-html="valueCtrl.val.value"></span> 
<span 
    ng-if="showButton && (!valueCtrl.show || !valueCtrl.reallyShow)" 
    class="show-button fa fa-eye animate-show animate-hide" aria-hidden="true" 
    title="Προβολή κωδικού"
    ng-click="valueCtrl.show = true"></span>
<span 
    ng-if="showButton && valueCtrl.show && valueCtrl.reallyShow" 
    class="show-button fa fa-eye-slash animate-show animate-hide" aria-hidden="true" 
    title="Απόκρυψη κωδικού"
    ng-click="valueCtrl.show = false"></span>
