<!--
/**
 * KtogiasZendLib (https://github.com/ktogias/KtogiasZendLib)
 *
 * @link      https://github.com/ktogias/KtogiasZendLib for the canonical source repository
 * @copyright Copyright (c) Konstantinos Togias (https://ktogias.gr)
 * @license   https://raw.githubusercontent.com/ktogias/KtogiasZendLib/master/LICENSE New BSD License
 */
-->
<div>
    <div class="form-group" ng-class="{'control-group': editForm, error: editForm && editControlName && editForm[editControlName].$invalid && !editForm[editControlName].$pristine}">
        <select class="form-control {{controlClass}}"
                   ng-attr-name="{{editControlName}}"
                   placeholder="{{editPlaceholder | translate}}"
                   ng-model="valueCtrl.editvalue"  
                   ng-required="editRequired"
                   ng-disabled="editDisabled"
                   >
                <option value="">---{{editPlaceholder| translate}}---</option>
                <option ng-repeat="rawVal in valuesMap" value="{{rawVal.key}}">{{rawVal.value | translate}}</option>
        </select>
    </div>
    <span ng-if="!editForm" ng-include="'values/edit-buttons.phtml'"></span>
    <span ng-show="(editValueForm.$error.required && !editValueForm.$pristine) || (editForm && editControlName && editForm[editControlName].$error.required && !editForm[editControlName].$pristine)" class="help-block error">
        {{'Επιλέξτε μια τιμή.' | translate}}
    </span>
    <span ng-repeat="error in editCustomErrors" 
          ng-show="(editValueForm.$error[error.name]  && !editValueForm.$pristine) || (editForm && editControlName && editForm[editControlName].$error[error.name] && !editForm[editControlName].$pristine)" class="help-block error">
        {{error.message | translate}}
    </span>
</div>

